apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commandservice
  template:
    metadata:
      labels:
        app: commandservice
    spec:
      containers:
        - name: commandservice
          image: adriana634/commandservice:latest
          env:
            - name: "RabbitMQ__Host"
              value: "rabbitmq-clusterip-service"
            - name: "RabbitMQ__Port"
              value: "5672"
            - name: "GrpcPlatform"
              value: "http://platform-clusterip-service:1480"
---
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: commandservice
  ports:
    - name: commandservice
      protocol: TCP
      port: 80
      targetPort: 80
