apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: adriana634/platformservice:latest
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Staging"
            - name: CommandService
              valueFrom:
                secretKeyRef:
                  name: platforms-env
                  key: CommandService
            - name: ConnectionStrings__Platforms
              valueFrom:
                secretKeyRef:
                  name: platforms-env
                  key: PlatformsDB
            - name: "RabbitMQ__Host"
              value: "rabbitmq-clusterip-service"
            - name: "RabbitMQ__Port"
              value: "5672"
            - name: "Kestrel__Endpoints__Grpc__Protocols"
              value: "Http2"
            - name: "Kestrel__Endpoints__Grpc__Url"
              value: "http://platforms-clusterip-service:1480"
            - name: "Kestrel__Endpoints__WebApi__Protocols"
              value: "Http1"
            - name: "Kestrel__Endpoints__WebApi__Url"
              value: "http://platforms-clusterip-service:80"
---         
apiVersion: v1
kind: Service
metadata:
  name: platform-clusterip-service
spec:
  type: ClusterIP
  selector: 
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 80
    - name: platformgrpc
      protocol: TCP
      port: 1480
      targetPort: 1480